<?php

declare(strict_types=1);

namespace NowoTech\ClaudePhpSetup\Template\Examples;

use NowoTech\ClaudePhpSetup\Question\ProjectConfig;

/**
 * Represents the ExampleTemplates class.
 */
final class ExampleTemplates
{
    /** @return array<string, string> key => relative path under examples/ */
    public static function all(ProjectConfig $config): array
    {
        return [
            'examples/README.md'                  => self::readme($config),
            'examples/workflows/feature.md'       => self::featureWorkflow(),
            'examples/workflows/bugfix.md'        => self::bugfixWorkflow(),
            'examples/prompts/review-pr.md'       => self::reviewPrompt(),
            'examples/prompts/add-command.md'     => self::addCommandPrompt(),
            'examples/prompts/add-agent-skill.md' => self::addAgentSkillPrompt(),
        ];
    }

    /**
     * Handles the readme operation.
     */
    private static function readme(ProjectConfig $config): string
    {
        $framework = $config->framework !== 'none' ? $config->framework : 'php';
        $testing   = $config->testingFramework;

        return <<<MD
        # Examples generated by Claude PHP Setup

        This folder contains practical examples to accelerate onboarding and daily usage.

        ## What is inside

        - `workflows/feature.md`: end-to-end example for implementing a feature.
        - `workflows/bugfix.md`: reproducible bugfix workflow with validation steps.
        - `prompts/review-pr.md`: high-quality PR review prompt template.
        - `prompts/add-command.md`: prompt to add a new slash command.
        - `prompts/add-agent-skill.md`: prompt to add/update agents and skills.

        ## Project context snapshot

        - Framework: {$framework}
        - PHP: {$config->phpVersion}
        - Testing: {$testing}
        MD;
    }

    /**
     * Handles the featureWorkflow operation.
     */
    private static function featureWorkflow(): string
    {
        return <<<'MD'
        # Workflow: implement a feature

        1. Clarify scope and acceptance criteria.
        2. Implement the smallest viable change.
        3. Add/adjust tests for the new behavior.
        4. Run QA locally (style, static analysis, tests).
        5. Prepare concise commit(s) and PR summary.

        ## Example prompt

        > Implement `<feature>` in `<module>`, preserving backward compatibility.
        > Include tests and update docs if behavior changes.
        MD;
    }

    /**
     * Handles the bugfixWorkflow operation.
     */
    private static function bugfixWorkflow(): string
    {
        return <<<'MD'
        # Workflow: bugfix

        1. Reproduce the bug with a minimal failing scenario.
        2. Add/adjust a test that fails before the fix.
        3. Apply the minimal code change.
        4. Verify with full QA.
        5. Document root cause and prevention.

        ## Example prompt

        > Fix `<bug>` in `<file/module>`.
        > Add regression tests and explain root cause in PR notes.
        MD;
    }

    /**
     * Handles the reviewPrompt operation.
     */
    private static function reviewPrompt(): string
    {
        return <<<'MD'
        # Prompt: review PR

        Review this branch with a code-review mindset:
        - prioritize bugs, regressions, risks, and missing tests
        - list findings by severity
        - include concrete fixes
        - keep summary short after findings

        Scope:
        - changed files only
        - preserve project conventions
        MD;
    }

    /**
     * Handles the addCommandPrompt operation.
     */
    private static function addCommandPrompt(): string
    {
        return <<<'MD'
        # Prompt: add slash command

        Add a new command template in `.claude/commands/` and wire it in the generator:
        - update command selection logic
        - add the template body
        - include tests for availability and content
        - keep backward compatibility
        MD;
    }

    /**
     * Handles the addAgentSkillPrompt operation.
     */
    private static function addAgentSkillPrompt(): string
    {
        return <<<'MD'
        # Prompt: add agent and skill

        Add one new agent and one new skill aligned to the current stack:
        - wire selection in wizard
        - generate files under `.claude/agents` and `.claude/skills/<name>/SKILL.md`
        - add tests for generation and filtering
        - keep template style consistent
        MD;
    }
}
